//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIV_ACT_Helper_Plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIV_ACT_Helper_Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   49|Medicated|強化薬|1|1|30|0|0|0|1
        ///141|Battle Voice|バトルボイス|1|2|20|0|0|20|0
        ///116|Life Surge|ライフサージ|1|1|5|0|100|0|0
        ///638|Vulnerability Up|被ダメージ上昇|2|1|15|5|0|0|0
        ///786|Battle Litany|バトルリタニー|1|2|20|0|10|0|0
        ///851|Reassemble|整備|1|1|5|0|100|100|0
        ///1177|Inner Release|原初の解放|1|1|10|0|100|100|0
        ///1185|Meditative Brotherhood|桃園結義：攻撃|1|2|15|5|0|0|0
        ///1213|Devotion|エギの加護|1|2|15|5|0|0|0
        ///1221|Chain Stratagem|連環計|2|1|15|0|10|0|0
        ///1297|Embolden|エンボルデン|1|2|20|10|0|0|4
        ///1454|Left Eye|竜の左眼|1|1|20|5|0|0|0
        ///1822|Technical Finish|テクニカ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Buffs {
            get {
                return ResourceManager.GetString("Buffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When checked, ACT will calculate FFLogs DPS/HPS for all zones.
        ///
        ///Cautions.
        ///- Performance may be degraded.
        ///- The values may significantly differ from those in the FFLogs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpCalculateFFLogsDPSHPSForAllZones {
            get {
                return ResourceManager.GetString("HelpCalculateFFLogsDPSHPSForAllZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When checked, ACT will count the use of medicated items (eg Tincture of Strength) and may view it on Encounter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpCountMedicatedBuffs {
            get {
                return ResourceManager.GetString("HelpCountMedicatedBuffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When checked, ACT will ONLY count the use of the latest and highest quality medicated items. (As of patch 5.4, the &quot;Grade 4 Tincture&quot; series) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpCountOnlyTheLatestAndHighQuality {
            get {
                return ResourceManager.GetString("HelpCountOnlyTheLatestAndHighQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse-over an item to view a more detailed explanation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpEmpty {
            get {
                return ResourceManager.GetString("HelpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If checked, ACT will end current combat in the event the content restarted due to all party members are incapacitated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpEndCombatWhenRestartContent {
            get {
                return ResourceManager.GetString("HelpEndCombatWhenRestartContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When checked, ACT will simulate FFLogs parses and may view perf, source DPS/HPS and DPS portions (given/taken DPS) on Encounter.
        ///
        ///Note: the currently supported zones are as follows.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HelpSimulateFFlogsParses {
            get {
                return ResourceManager.GetString("HelpSimulateFFlogsParses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0A|Potion of Strength|33559026
        ///0B|Potion of Dexterity|33559027
        ///0C|Potion of Vitality|33559028
        ///0D|Potion of Intelligence|33559029
        ///0E|Potion of Mind|33559030
        ///10|Hi-Potion of Strength|33559031
        ///11|Hi-Potion of Dexterity|33559032
        ///12|Hi-Potion of Vitality|33559033
        ///13|Hi-Potion of Intelligence|33559034
        ///14|Hi-Potion of Mind|33559035
        ///1D|Mega-Potion of Strength|33559036
        ///1E|Mega-Potion of Dexterity|33559037
        ///1F|Mega-Potion of Vitality|33559038
        ///20|Mega-Potion of Intelligence|33559039
        ///21|Mega-Potion of Mind [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MedicatedItems {
            get {
                return ResourceManager.GetString("MedicatedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin Exited. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePluginDeinit {
            get {
                return ResourceManager.GetString("MessagePluginDeinit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugin Started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePluginInit {
            get {
                return ResourceManager.GetString("MessagePluginInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an updated version of the FFXIV ACT Helper Plugin. Update it now?
        ///
        ///(If there is an update to ACT, you should click Cancel and update ACT first.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePluginUpdate {
            get {
                return ResourceManager.GetString("MessagePluginUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFXIV ACT Helper Plugin was updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePluginUpdateCompleted {
            get {
                return ResourceManager.GetString("MessagePluginUpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred while updating FFXIV ACT Helper Plugin: 
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePluginUpdateError {
            get {
                return ResourceManager.GetString("MessagePluginUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   53|Bootshine|連撃|100|0
        ///2246|Assassinate|終撃|100|0
        ///16463|Chaotic Cyclone|カオティックサイクロン|100|100
        ///16465|Inner Chaos|インナーカオス|100|100 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
    }
}
